name dash-exploration
dependencies:
  - python=3.6
  - pip:
    - dash
    - dash-renderer
    - dash-core-components
    - dash-html-components
    - plotly
    - gunicorn
    - dash-auth
    - dash-bootstrap-components
    - pandas-datareader
